name: ssl_pinning_plugin
description: SSL Pinning for request HTTP.
version: 0.0.1
author: Macif <contact.appmobile@macif.fr>
homepage: https://github.com/macif-dev/ssl_pinning_plugin

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.macif.plugin.sslpinningplugin
    pluginClass: SslPinningPlugin

environment:
 sdk: ">=2.0.0-dev.68.0 <3.0.0"
